# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100)),
                ('mail', models.TextField(blank=True, max_length=100)),
                ('mobile', models.IntegerField()),
                ('worktype', models.TextField(blank=True, max_length=20)),
                ('work', models.TextField(blank=True, max_length=1000)),
                ('file', models.FileField(upload_to='orders/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
