# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prof_mail',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='prof_name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
