# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approval1',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='approval2',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='approval3',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=1),
        ),
    ]
