# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180331_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver2', models.TextField(max_length=100)),
                ('approver3', models.TextField(max_length=100)),
            ],
        ),
    ]
