# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180331_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
