# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
