# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180403_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
