# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_status_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reason',
        ),
        migrations.AddField(
            model_name='order',
            name='remarks1',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='remarks2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='remarks3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
