# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180529_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approval1',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('May be', 'May be')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='approval2',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('May be', 'May be')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='approval3',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('May be', 'May be')], default='Pending', max_length=10),
        ),
    ]
